server:
  port: 7000

eureka:
  # 关闭Eureka自动保护机制，宁可不健康也保留，防止网络波动
#  server:
#    enable-self-preservation: false
  instance:
    hostname: eureka7000.com #表示主机名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #fasle表示自己端就是注册中心,我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 单机实例
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 集群配置

