server:
  port: 9010

mybatis:
  configuration:
    mapUnderscoreToCamelCase: false
    callSettersOnNulls: true
  mapper-locations: classpath:mybatis/mapper/*.xml

# 客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/,http://localhost:7001/eureka/,http://localhost:7002/eureka/
    instance-id: spring-cloud-provider-dept-hystrix
    prefer-ip-address: true # 访问路径可以显示IP地址

spring:
  application:
    name: spring-cloud-provider-dept
  datasource:
    # DB2 Basic Setting
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://cwtch.yiroote.com/cloud
    username: root
    password: aXUAN117323
    # Druid
    druid:
      aop-patterns: com.alibaba.druid.spring.boot.demo.com.ibm.liuxhe.service.*
      async-close-connection-enable: true
      initial-size: 1
      min-idle: 1
      max-active: 2
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM dept
      validation-query-timeout: 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: false
          slow-sql-millis: 2000
      stat-view-servlet:
        enabled: false
      web-stat-filter:
        enabled: false
  jpa:
    show-sql: true

info:
  app.name: spring-cloud-provider-dept
  company.name: ibm
  build.artifactId: $project.artifactId$
  build.version: $project.version$